title: OrthoFinder Tutorials
remote_theme: just-the-docs/just-the-docs@v0.5.3

# ✨ Hide search bar
search_enabled: false

# 🎨 Optional theme (choose: light, dark, medium)
color_scheme: light

# 🔗 Add a link in the top-right of the site
aux_links:
  "GitHub Repo":
    - "https://github.com/OrthoFinder/OrthoFinder"
