title: OrthoFinder Tutorials
remote_theme: just-the-docs/just-the-docs@v0.5.3

# Disable the search bar
search_enabled: false

# Optional link in top-right corner
aux_links:
  "GitHub Repo":
    - "https://github.com/lauriebelch/OrthoDocs"

# Load custom CSS
sass:
  style: compressed
  load_paths:
    - assets/css

# Enable a logo if you want (optional)
# logo: /assets/img/logo.png
