title: OrthoFinder Tutorials
remote_theme: just-the-docs/just-the-docs@v0.5.3

search_enabled: false

# Optional GitHub repo link in header
aux_links:
  "GitHub Repo":
    - "https://github.com/OrthoFinder/OrthoFinder"

# Load custom CSS (important!)
plugins:
  - jekyll-sass-converter

sass:
  style: compressed
  load_paths:
    - assets/css
