title: OrthoFinder Tutorials
remote_theme: just-the-docs/just-the-docs@v0.5.3

search_enabled: false

# SCSS support — this is how you load your styles
callouts:
  note:
    title: Note
    color: blue

# Where to find your custom SCSS
sass:
  load_paths:
    - assets/css
