title: OrthoFinder
remote_theme: just-the-docs/just-the-docs@v0.5.3

search_enabled: false

color_scheme: light

nav:
  - Understanding Orthology: orthology.md
  - Beginner Tutorial: beginner.md
  - Getting Input Data: input.md
  - Guide to Results Files: results.md
  - Advanced Tutorial: advanced.md
  - Advanced Usage: usage.md
  
# GitHub repo link in header
aux_links:
  "GitHub Repo":
    - "https://github.com/OrthoFinder/OrthoFinder"
