title: OrthoFinder Tutorials
remote_theme: just-the-docs/just-the-docs@v0.5.3

search_enabled: false  # ⛔ Disables search bar

# Sidebar tweaks
aux_links:
  "GitHub Repo":
    - "https://github.com/lauriebelch/OrthoDocs"

# Navigation bar width (CSS tweak below will reduce it)
